import Head from "next/head";
import useMQTT from "../useMQTT";
import { useState } from "react";
export default function Home() {
  const [text, setText] = useState("");

  const { mqttMessage, mqttStatus } = useMQTT("honarestan/naft/test1");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          flexFlow: "column nowrap",
          gap: "20px",
          minHeight: "100vh",
          padding: "30px",
        }}
      >
        <textarea
          id="input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          style={{ minHeight: "50px", padding: "30px" }}
        />
        <button
          id="button"
          style={{ height: "30px", inlineSize: "100px", marginInline: "auto" }}
        >
          Click me
        </button>

        <textarea value={mqttMessage} style={{ color: "red" }} />
      </main>
    </>
  );
}
